### ISSUE TITLE
Registration is failing

### ISSUE THREAD

**Issue by MarkusAurelius** [future-coop/future-bonus-app#1]
On 20th of August I recognized in the morning that I was logged out. Then I tried to register again - to no avail. I got the error message, that my E-Mail address isnt' existing (or something similar) Only after a re-installing the Transition App the the registration worked again. I observed this behavior on my Mobile Device already twice (Huawei P10, Android 7.1).
I received two reports from other test persons (marinus.maier@gmail.com, p_susanne@hotmail.de) as well today that their registration failed as well although their email addresses are entered in the Firebase Autentication Database.
Transition-App-Version 1.0.4.

Please get in touch with me in case you need more detailed information.
Could you please investigate?

**Comment by benediktdertinger** [comment]
Hi @MarkusAurelius1976, we are able to reproduce this on Android devices. Not sure what is the exact problem but we can use the stack trace to find the error. I will try to fix it tomorrow.

**Comment by simonkoehl** [comment]
@benediktdertinger Can I close the issue?
