### ISSUE TITLE
Change wording in transactions list

### ISSUE THREAD

**Issue by sonja-retzlaff** [future-coop/future-bonus-app#10]
Write "Erfolgreich erfasst" instead of "Erfolgreich hochgeladen"

**Comment by benediktdertinger** [comment]
@sonja-retzlaff these will be the new statuses:

```js
     case 'sent':
        text = 'Erfolgreich erfasst';
        color = 'success';
        break;
      case 'failed':
        text = 'Erfassung fehlgeschlagen';
        color = 'danger';
        break;
      case 'pending':
        text = 'Warte auf Erfassung...';
        color = 'warning';
        break;
      case 'sending':
        text = 'Erfasse...';
        color = 'info';
        break;
```
Do they meet your requirements?

**Comment by sonja-retzlaff** [comment]
@benediktdertinger I guess this refers to the notifications that Bonus app users see when trying to scan an QR code with the app? From my point of view it makes sense like that. @simonkoehl what do you think?
