### ISSUE TITLE
Add loyalty partners list in app - filtered by chapter

### ISSUE THREAD

**Issue by sonja-retzlaff** [future-coop/future-bonus-app#2]
The user should be able to see in the app which partners participate in the loyalty program and where they are located. 

Partner should be listed with:
- Title
- Image
- Need(s)
- Description
- Address (Link to map)
- Discount 

UI
- Tabs: local|online
- Local partners: Filter by need + city
- Online shops: Show coupon codes (load from JSON file)
- Highlights: #Info about new partners added #9 
- Lazy load list
- Sequence:
1. Latest (2 months) with highlight at the beginning
2. Very sustainable (random)
3. Sustainable (random)

Add selection of chapter -> filter list by chapter

**Comment by sonja-retzlaff** [comment]
The user should be able to see in the app which partners participate in the loyalty program and where they are located. This could easily be achieved by linking to the respective map entries

**Comment by simonkoehl** [comment]
@benediktdertinger 

**Situation**
My understanding is, that the discount information for loyalty partners in the map is just saved in a string. 

**Problem**
In Berlin and in the future we are going to have other discounts than 5%. 

**Possible Solution**
Should we save additional information in the database regarding the discount? So we can generate the correct information for the user.

**Comment by benediktdertinger** [comment]
Currently we are able to store additional data attributes in each entry in the Good Database related to different providers. This way it should be easily handable to set a default discount (e.g. 5%) and overwrite it if specific values have been defined (e.g. 7%) or region-based by overwriting all discounts for Berlin by e.g. 6%.

**Comment by simonkoehl** [comment]
Sounds good!
