### ISSUE TITLE
Change FAQ link and test on start screen

### ISSUE THREAD

**Issue by simonkoehl** [future-coop/future-bonus-app#23]
pls change link to o https://future.coop/bonus-faq (PDF is going to be replaced)

pls change text on start screen to:

Und so geht's:

Nach dem Bezahlen in Partner-Läden einfach sagen, dass du Mitglied bei Future bist. Die Kassenkraft zeigt dir einen QR-Code, den du mit dieser App scannen kannst. Anschließend erscheint die Ermäßigung auf deinem Konto. 

Wir haben hier Antworten auf die häufigsten Fragen zusammengestellt:

**Comment by simonkoehl** [comment]
Eine Sache ist mir auf dem Screen gerade noch aufgefallen: Lass uns ganz oben "München" rausnehmen, dann ist es gleich neutral, falls wir einen Testlauf in Berlin starten. Und gleich die Vision bisschen vorweg nehmen mit Onlineshops und spenden

**Vorschlag**
"Spare Geld oder sammle Spenden mit deinem Einkauf in nachhaltigen Läden und Onlineshops."

**Comment by benediktdertinger** [comment]
Habe es entsprechend angepasst.
