### ISSUE TITLE
landing page - small changes

### ISSUE THREAD

**Issue by simonkoehl** [future-coop/future-bonus-app#26]
**Einkaufen im Laden**
Gib beim Bezahlen einfach Bescheid, dass du Mitglied bei Future bist. Die Kassenkraft zeigt dir dann einen QR Code, den du mit der App scannst. Anschließend erscheint dein Bonus unter “Transaktionen”.

[Code Scannen]

**Einkaufen im Onlineshop**
Alle Onlineshops und die zugehörigen Rabattcodes findest du hier:

[Onlineshops & Rabattcodes](pls contact @elbotho regarding the link)

**Noch Fragen?**
Wir haben hier Antworten auf die häufigsten Fragen zusammengestellt:

[Fragen & Antworten]

**Feedback?**
Solltest du Fehler entdecken, Kritik oder Lob äußern wollen, nutze gerne unser Feedback Formular:

[Feedback geben]

**Comment by benediktdertinger** [comment]
<img width="584" alt="Screenshot 2020-04-23 at 10 29 08" src="https://user-images.githubusercontent.com/6225675/80077081-4d0e9a00-854d-11ea-8b34-7824f56c39f5.png">
”Onlineshops & Rabattcodes“ is too long. I reduced it to “Rabattcodes” @simonkoehl , ok?

**Comment by simonkoehl** [comment]
Looks good! Yes "Rabattcodes" is fine I guess.
